### PR TITLE
Updated submit form UI

### PR DESCRIPTION
**Pull request by Doc415**

### CODE REVIEW

**Comment by TheCSharpAcademy** [comment]
@Doc415 Is there an issue in the academy for this one? 😊

**Comment by Doc415** [comment]
> @Doc415 Is there an issue in the academy for this one? 😊



> @Doc415 Is there an issue in the academy for this one? 😊

Yes i think so this should be the issue in the academy
image

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@Doc415 Could you please fix conflicts so I can jump on it today? 🤓 Thank you.

**Comment by Doc415** [comment]
> @Doc415 Could you please fix conflicts so I can jump on it today? 🤓 Thank you.

Rebased on origin and fixed conflict with selecting incoming

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@Doc415 😆😆 Might be better doing a new PR

image

**Pull request closed without merging**
