### PR TITLE
Turkish translation

### PR DESCRIPTION
**Pull request by Doc415**

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@Doc415 Could you please fix the conflicts? Dev branch was updated. 

It's a great exercise to feel what we feel on a daily basis at work 😂😂

**Comment by Doc415** [comment]
conflicts resolved :)

**Comment by stevietv** [comment]
It looks like you added all the commits. What you really needed to do was - pull down the latest version of Develop into your local Develop branch, then with your own branch checked out, rebase that onto the dev branch.

**Comment by Doc415** [comment]
> It looks like you added all the commits. What you really needed to do was - pull down the latest version of Develop into your local Develop branch, then with your own branch checked out, rebase that onto the dev branch.
> 
> 
> 
> 

Thats what i did
Then i used vs merge editor to fix them and pushed to my branch

**Comment by stevietv** [comment]
to me it looks like you merged develop into your branch, instead of rebasing your branch onto develop

**Comment by Doc415** [comment]
> to me it looks like you merged develop into your branch, instead of rebasing your branch onto develop

Next time i ll call you and we do it together

**Pull request closed without merging**
