### PR TITLE
Add dark mode

### PR DESCRIPTION
**Pull request by antonderegt**
# Dark mode
After investigation of a few ways to deal with dark mode, I think using JS Interop to toggle dark/light mode classes will work nicely. It seems the solution suggested in issue #214 only works if you use pure Bootstrap. The JS way does require that all hardcoded CSS colors need to be updated to use a variable. Since there aren't too many different colors, I think this is fine. 

## How it works
On every navigation change `window.updateTheme` get called (located in `js/themeSwitcher.js`). This method adds or removes the `dark-theme` CSS class. In `app.css` you can find `:root { ... }` which holds the default colors. When the `dark-theme` class is applied, these variables are updated to represent the dark theme. To use the colors in CSS you can use the following: `color: var(--text-color);`.

It follows your system settings (not browser settings). With the following instructions you can switch between dark and light mode:

**On macOS:**
Open System Preferences (you can find it in the Apple menu or in the Dock).
Click on "General".
In the "Appearance" section at the top, select "Light" or "Dark".

**On Windows:**
Open Settings (you can find it in the Start menu).
Click on "Personalization".
Click on "Colors" in the left sidebar.
In the "Choose your color" dropdown, select "Light" or "Dark".

## Looks
It will look something like this:
Screenshot 2024-04-16 at 21 43 06

## Known issues
`Accounts` and `Admin` pages don't work with the current setup, because those pages are not compatible with rendermode `InteractiveServer`.

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@antonderegt Great work! Quick question, would it be possible to keep those pictures but without a background? I had so much trouble centering these (😂) that I had to create an image with icon and text.
image

**Comment by antonderegt** [comment]
> @antonderegt Great work! Quick question, would it be possible to keep those pictures but without a background? I had so much trouble centering these (😂) that I had to create an image with icon and text. image

Hey @TheCSharpAcademy for you anything is possible 😉 . I think I figured it out with CSS, is that also fine? The reason I split the logo from the text is that the black text wasn't readable on the dark background. 

With the last commit, the text will be vertically aligned with the logo:
Screenshot 2024-04-25 at 04 52 15

If this is not what you meant, I'm happy to keep the images with the text. I think I'll have to create two version of the images with dark and light text.

**Comment by TheCSharpAcademy** [comment]
@antonderegt I'm going to merge this but could you please fix the conflict? Should be a one-liner 😊

**Comment by antonderegt** [comment]
> @antonderegt I'm going to merge this but could you please fix the conflict? Should be a one-liner 😊

@TheCSharpAcademy that's so cool! I fixed the merge conflict 🥳

**Comment by TheCSharpAcademy** [comment]
@antonderegt I've merged it but there are a few issues, could you please create a separate PR: 
image

The leads after your changes are all black. Could you please change them to #1d256e
image

And this title should be
image

**Comment by antonderegt** [comment]
> @antonderegt I've merged it but there are a few issues with colors, could you please create a separate PR: image
> 
> The leads after your changes are all black. Could you please change them to #1d256e image
> 
> And this title should be image

You got a sharp eye 😉 . Check out this PR: #246

**Pull request merged**
