### PR TITLE
Release back review completed

### PR DESCRIPTION
**Pull request by Doc415**
Completed release review option. 
I could not completely test it, because it could not saved the created code review to db localy

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@Doc415 Sorry to mess around with you but could you please fix the conflicts once again? I finally have time to review 😁

**Comment by Doc415** [comment]
> @Doc415 Sorry to mess around with you but could you please fix the conflicts once again? I finally have time to review 😁

I rebased the branch on development
I wish it works 😁

**Comment by TheCSharpAcademy** [comment]
@Doc415 did it work when you first did it? There are tons of changes again 😟 Could you fix it one more time? I'll definitely review now.

**Comment by TheCSharpAcademy** [comment]
@Doc415 Closing for admin purposes. Feel free to reopen when you're ready 😁

**Pull request closed without merging**
