### PR TITLE
Navmenu closes when on location change

### PR DESCRIPTION
**Pull request by BBualdo**

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@BBualdo Really sorry but could you please fix the conflicts and send a picture of what the expected outcome? Thanks heaps! 😁😁

**Comment by BBualdo** [comment]
@TheCSharpAcademy Expected outcome is to close nav menu when user clicks any possible option. For example when user selects Dashboard in Menu, it should close menu, but it didn't 😂

**Comment by TheCSharpAcademy** [comment]
@BBualdo Should it work for the sub-menu? It's still there after I click on a link. 
image

**Comment by BBualdo** [comment]
@TheCSharpAcademy Unfortunately, I couldn't figure out how sub-menu works. I was first time I saw menu switched by <input /> 😅

**Pull request merged**
