### PR TITLE
Removed retired entries

### PR DESCRIPTION
**Pull request by Fennikko**
Removed "Simple Queries" and "Setting Criteria Using the Where Clause" from SqlProjectsHelper.cs

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@Fennikko Thanks for submitting! 

Unfortunately we can't remove the projects, since many people have completed them and it would cause a null error when trying to load their completed projects. Try looking into where these projects are being loaded and add a .Where(x => !x.isClosed) to the logic. Let me know if you have questions 🤓

**Comment by Fennikko** [comment]
Should be good now, thank you for taking the time to still let me correct and fix the issue!

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@Fennikko almost there! Everyone's projects are still loaded from GetProjects(), which means they're essentially unavailable if you put the check there 🥹 So it will be better if the check is where they're actually being loaded (I believe the dashboard?).

This is a good example of what happens when you're working on someone else's (poorly documented) code and flying semi-blind, and it will prepare you for the frustrations of enterprise development.  I often had the same piece of code reviewed and sent back to me 10s of times in my first job .😆😆 (blessed be my patient first manager)

**Comment by Fennikko** [comment]
I remove the .where from ProjectHelper.cs and added it to Dashboard.razor I had to cast it to a Project list to get it to work properly. I hope this time is correct! This is a really good learning experience!

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@Fennikko I believe you can chain a .ToList() at the end to avoid casting 🤓

**Comment by TheCSharpAcademy** [comment]
@Fennikko Let me know if you need help 😊

**Comment by Fennikko** [comment]
Changed Projects from a List to an IEnumerable, and this allowed me to use a where lambda statement without casting. Apologies for the delay, had some real life stuff get in the way of me working on projects.

**Pull request merged**
