### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by antonderegt**
PR fixes typo in Personal Flagship Project.

@TheCSharpAcademy please let me know if this is too small for a PR. Is it okay? Or do you prefer I just mention such small things in the feedback channel on Discord.

### CODE REVIEW

**Comment by TheCSharpAcademy** [comment]
@antonderegt It's ok, but could you please create an issue in the academy. You submitted the actual Flagship project 😂

**Comment by antonderegt** [comment]
> @antonderegt It's ok, but could you please create an issue in the academy. You submitted the actual Flagship project 😂

@TheCSharpAcademy huh, are you sure? I'm pretty sure I only submitted it as an issue. 
Screenshot 2024-05-02 at 09 30 29

Screenshot 2024-05-02 at 09 31 58

By the way, same issue as before. The issues get unsubmitted.

**Comment by antonderegt** [comment]
@TheCSharpAcademy ah, maybe it makes sense. First you approved another issue that I submitted. That made the submit for this issue disappear. Maybe that's it? I resubmitted it.

Also, the dark mode stayed in submitted state. So, this probably only happens when someone submits multiple issue of the same type.

**Comment by TheCSharpAcademy** [comment]
@antonderegt I think we have a bug affecting the visibility of some issues in my admin area, so all good in your end 😊 
image

**Pull request merged**
